http:
  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "benson:$apr1$O1f3HVwq$4.CPyV0cFXEACFhO3keUk0"
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: false
        port: 5443
    custom-headers:
      headers:
        contentTypeNosniff: true
        browserXSSFilter: true
        sslRedirect: true
    content-compress:
      compress: {}
    behind-proxy-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-For"

  services:
    # tricks
    # https://github.com/containous/traefik/issues/4863#issuecomment-491093096
    dummy:
      loadBalancer:
        servers:
          - url: "" # or url: "localhost"
    dsphoto:
      loadBalancer:
        servers:
          - url: "http://nas.example.com"
    nas:
      loadBalancer:
        servers:
          - url: "http://nas.example.com:5000"

  routers:
    https-redirect:
      entryPoints:
        - http
      rule: "HostRegexp(`{any:.*}`)"
      service: "dummy"
      middlewares:
        - "https-redirect"
    dashboard:
      entryPoints:
        - https
      service: api@internal
      middlewares: ["basic-auth", "https-redirect"]
      rule: "Host(`admin.example.com`)"
      tls: {}
    dsphoto:
      entryPoints:
        - https
      service: dsphoto
      rule: "Host(`photo.example.com`)"
      tls: {}
    nas:
      entryPoints:
        - https
      service: nas
      rule: "Host(`www.example.com`)"
      tls:
        certResolver: le
        domains:
          - main: "*.example.com"
            sans:
              - "example.com"
              - "*.example.com"
