http:
  services:
    dsphoto:
      loadBalancer:
        servers:
          - url: "http://photo.example.com"
      nas:
        loadBalancer:
          servers:
            - url: "http://nas.example.com:5000"
  routers:
    dsphoto:
      entryPoints:
        - https
      service: dsphoto
      rule: "Host(`photo.example.com`)"
      tls: {}
    nas:
      entryPoints:
        - https
      service: nas
      rule: "Host(`www.example.com`)"
      tls:
        certResolver: le
        domains:
          - main: "*.example.com"
            sans:
              - "example.com"
              - "*.example.com"
