version: "3"
services:
  gerrit:
    build: "image"
    image: "bensonfx/gerrit:3.3.2"
    restart: unless-stopped
    hostname: "review.example.com"
    depends_on:
      - ldap
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "29418:29418"
    volumes:
      - ./wwwroot/review_site:/var/gerrit/review_site
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # middlewares
      - "traefik.http.middlewares.custom-headers.headers.contentTypeNosniff=true
      - "traefik.http.middlewares.custom-headers.headers.browserXSSFilter=true
      - "traefik.http.middlewares.custom-headers.headers.sslRedirect=true
      - "traefik.http.middlewares.basic-auth.basicauth.usersfile=/data/ssl/passwd.db"
      # services
      - "traefik.http.services.gerrit.loadBalancer.server.port=8080"
      - "traefik.http.services.gerrit.loadBalancer.server.scheme=http"
      # routers
      - "traefik.http.routers.gerrit-web.middlewares=https-redirect@file"
      - "traefik.http.routers.gerrit-web.entrypoints=http"
      - "traefik.http.routers.gerrit-web.rule=Host(`$GERRIT_DOMAIN_NAME`)"
      - "traefik.http.routers.gerrit-web.service=gerrit"
      - "traefik.http.routers.gerrit-https.middlewares=custom-headers,basic-auth"
      - "traefik.http.routers.gerrit-https.rule=Host(`$GERRIT_DOMAIN_NAME`)"
      - "traefik.http.routers.gerrit-web.entrypoints=https"
      - "traefik.http.routers.gerrit-https.tls=true"
      - "traefik.http.routers.gerrit-https.service=gerrit"
  ldap:
    image: osixia/openldap
    domainname: "ldap.example.com"
    hostname: "ldap.example.com"
    ports:
      - "389:389"
      - "636:636"
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
      LDAP_ORGANISATION: "Your Comany"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "your_ldap_password"
      LDAP_CONFIG_PASSWORD: "your_ldap_passwrd"
      LDAP_BACKEND: "mdb"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
    volumes:
      - ./wwwroot/ldap/database:/var/lib/ldap
      - ./wwwroot/ldap/config:/etc/ldap/slapd.d
      - ./wwwroot/certificates:/container/service/slapd/assets/certs
  lam:
    build: lam
    image: bensonfx/lam
    volumes:
      - ./wwwroot/lam:/wwwroot
    working_dir: /wwwroot
