version: "3.5"
services:
  gerrit:
    build: "image"
    image: "bensonfx/gerrit:2.16.8"
    restart: unless-stopped
    hostname: "review.example.com"
    depends_on:
      - ldap
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "29418:29418"
    volumes:
      - ./wwwroot/review_site:/var/gerrit/review_site
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.passTLSCert=false"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.rule=Host:review.example.com"
      - "traefik.frontend.auth.basic.usersFile=/data/ssl/passwd.db"
      - "traefik.frontend.entryPoints=https,http"
  ldap:
    image: osixia/openldap
    domainname: "ldap.example.com"
    hostname: "ldap.example.com"
    ports:
      - "389:389"
      - "636:636"
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"
      LDAP_ORGANISATION: "Your Comany"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "your_ldap_password"
      LDAP_CONFIG_PASSWORD: "your_ldap_passwrd"
      LDAP_BACKEND: "mdb"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
    volumes:
      - ./wwwroot/ldap/database:/var/lib/ldap
      - ./wwwroot/ldap/config:/etc/ldap/slapd.d
      - ./wwwroot/certificates:/container/service/slapd/assets/certs
  lam:
    build: lam
    image: bensonfx/lam
    volumes:
      - ./wwwroot/lam:/wwwroot
    working_dir: /wwwroot
