version: '3'
services:
  traefik:
    container_name: traefik-v2
    image: traefik:v2.3
    command: traefik --configFile /etc/traefik.yml
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider localhost:8080/ping || exit 1"]
    command: traefik --configFile /etc/traefik.yml
    environment:
      TZ: "Asia/Shanghai"
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik.yml:ro
      - ./conf:/etc/traefik/conf:ro
      - ./ssl:/data/ssl
      - ./logs:/logs
    ports:
    - "80:80"
    - "443:443"
    labels:
    - "traefik.docker.network=traefik"
    - "traefik.http.routers.traefik.service=api@internal"
    networks:
    - "traefik"
  # ldap:
  #   image: osixia/openldap
  #   domainname: "ldap.example.com"
  #   hostname: "ldap.example.com"
  #   ports:
  #   - "389:389"
  #   - "636:636"
  #   restart: unless-stopped
  #   environment:
  #     TZ: "Asia/Shanghai"
  #     LDAP_ORGANISATION: "example.com"
  #     LDAP_DOMAIN: "example.com"
  #     LDAP_ADMIN_PASSWORD: "oUT5DngfuLqr9KRwVh1w+e"
  #     LDAP_CONFIG_PASSWORD: "eHNntGgELAFWzqavH/1ii6"
  #     LDAP_TLS_CRT_FILENAME: "example.com.crt"
  #     LDAP_TLS_KEY_FILENAME: "example.com.key"
  #     LDAP_TLS_CA_CRT_FILENAME: "alpha_ca.crt"
  #     LDAP_TLS_VERIFY_CLIENT: "never"
  #   volumes:
  #   - ./data/ldap/database:/var/lib/ldap
  #   - ./data/ldap/config:/etc/ldap/slapd.d
  #   - ./data/ssl:/container/service/slapd/assets/certs
  # lam:
  #   image: bensonfx/lam
  #   volumes:
  #   - "./data/lam:/wwwroot/lam"
  #   working_dir: /wwwroot
  # web:
  #   image: bensonfx/caddy:0.11.1
  #   restart: always
  #   environment:
  #     CADDY_SERVER: http://ldap.example.com
  #     CADDY_ROOT: /wwwroot/lam
  #     FASTCGI_PATH: lam:9000
  #   volumes:
  #     - "./data/lam:/wwwroot/lam"
  #   labels:
  #   - "traefik.enable=true"
  #   - "traefik.port=80"
  #   #- "traefik.protocol=http"
  #   - "traefik.frontend.passHostHeader=true"
  #   - "traefik.frontend.headers.contentTypeNosniff=true"
  #   - "traefik.frontend.headers.browserXSSFilter=true"
  #   - "traefik.frontend.rule=Host:ldap.example.com"
  #   - "traefik.docker.network=traefik"
  #   ports:
  #   - "8080:80"
  #   networks:
  #   - "traefik"
  #   - "default"
networks:
  traefik:
    external: true
