version: '3.5'
services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/etc/traefik/traefik.toml
      - ./data/ssl:/data/ssl
      - ./data/logs:/data/logs
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.docker.network=traefik"
networks:
  default:
    name: traefik
