version: '3.5'
services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/etc/traefik/traefik.toml
      - ./data/ssl:/data/ssl
      - ./data/logs:/data/logs
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.frontend.passHostHeader=true"
  prom:
    image: prom/prometheus:v2.5.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
networks:
  default:
    name: traefik
