global:
  checkNewVersion: false
  sendAnonymousUsage: false
api:
  dashboard: true
  debug: true
ping: {}
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "172.18.0.0/24"
        - "192.168.31.0/24"
log:
  level: WARN
  filePath: "/logs/traefik.log"
  format: json
accessLog:
  filePath: "/logs/access.log"
  format: json
providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ normalize .Name }}.example.com`)"
    exposedbydefault: false
    network: traefik
    usebindportip: false
    swarmmode: false
    # tls:
    #   ca: "/etc/ssl/ca.crt"
    #   cert: "/etc/ssl/docker.crt"
    #   key: "/etc/ssl/docker.key"
    #   insecureSkipVerify: true
  file:
    directory: "/etc/traefik/conf"
    watch: true
    debugLogGeneratedTemplate: true
certificatesResolvers:
  le:
    acme:
      email: admin@example.com
      storage: /data/ssl/acme.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 15
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
