################################################################
# 全局设置
################################################################
# 激活调试模式 （默认关闭）
# debug = true
# 不上报统计信息
sendAnonymousUsage = false
# 全局入口点类型 （默认 http）
defaultEntryPoints = ["http", "https"]

[api]
  entryPoint = "traefik-api"
# 开启控制台（默认开启）
  dashboard = true
# 默认协议
  defaultEntryPoints = ["http"]
# 启用 ping
[ping]
  # 入口点名称
  entryPoint = "traefik-ping"

# Metrics definition
[metrics]
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
    # Name of the related entry point
    #
    # Optional
    # Default: "traefik"
    #
    entryPoint = "traefik-metrics"
    # Buckets for latency metrics
    #
    # Optional
    # Default: [0.1, 0.3, 1.2, 5]
    #
    buckets = [0.1,0.3,1.2,5.0]
################################################################
# 入口点设置
################################################################
[entryPoints]
    [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      compress = true
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      sniStrict = true
      [[entryPoints.https.tls.certificates]]
        certFile = "/data/ssl/bensonfx.cc.crt"
        keyFile = "/data/ssl/bensonfx.cc.key"
    # 控制台端口
    [entryPoints.traefik-api]
      address = ":8081"
      # 配置生成BA账号密码
      [entryPoints.traefik-api.auth]
        [entryPoints.traefik-api.auth.basic]
          #htpasswd -nb benson benson
          users = ["benson:$apr1$Ghub3u8x$oz0Tgyt20DgQ.LFdy8df40"]
        [entryPoints.traefik-api.redirect]
          entryPoint = "https"
      [entryPoints.traefik-api.whiteList]
        sourceRange = ["192.168.31.0/24", "10.0.0.0/24", "192.168.96.0/20"]
        useXForwardedFor = true
    # Ping端口
    [entryPoints.traefik-ping]
      address = ":8082"
      [entryPoints.traefik-ping.redirect]
        entryPoint = "https"
    [entryPoints.traefik-metrics]
      address = ":8083"
################################################################
# 日志设置
################################################################
# 日志等级 （默认 ERROR）
logLevel = "INFO"
[traefikLog]
  filePath = "/data/logs/traefik.log"
  format   = "json"
[accessLog]
  filePath = "/data/logs/access.log"
  format = "json"
################################################################
# Docker 后端配置
################################################################
# 启用Docker后端
[docker]
# Docker服务后端
endpoint = "unix:///var/run/docker.sock"
# 默认域名
domain = "bensonfx.cc"
# 监控docker变化
watch = true
# 使用自定义模板（可选）
# filename = "docker.tmpl"

# 对容器默认进行暴露（默认开启）
#   如果关闭选项，则容器不包含 `traefik.enable=true` 标签，就不会被暴露
exposedbydefault = false
# 使用绑定端口的IP地址取代内部私有网络（默认关闭）
usebindportip = false
# 使用 Swarm Mode （默认关闭）
swarmmode = false
# 默认网络, 可以使用 traefik.docker.network 标签覆盖
# network = "web"
# Enable docker TLS connection.
#
# Optional
#
#  [docker.tls]
#  ca = "/etc/ssl/ca.crt"
#  cert = "/etc/ssl/docker.crt"
#  key = "/etc/ssl/docker.key"
#  insecureSkipVerify = true
################################################################
# Traefik File configuration
################################################################
[file]
[backends]
  [backends.dashboard]
    [backends.dashboard.servers.server0]
      url = "http://localhost:8081"
  [backends.ping]
    [backends.ping.servers.server0]
      url = "http://localhost:8082"
[frontends]
  [frontends.dashboard]
    backend = "dashboard"
    [frontends.dashboard.routes.route0]
      rule = "Host:admin.bensonfx.cc"
  [frontends.ping]
    backend = "ping"
    [frontends.ping.routes.route0]
      rule = "Host:ping.bensonfx.cc"
    [frontends.ping.routes.route1]
      rule = "ReplacePathRegex: ^/ /ping"
