version: '3'

services:
  aria2:
    image: bensonfx/aria2-ui
    build: aria2
    ports:
      - "6800:6800"
    volumes:
      - ./data/user-files:/data
    #   - ./data/ssl:/root/conf/ssl
    environment:
      - CADDY_SERVER=:80
      - CADDY_ROOT=/var/www/html/aria2
      # - ARIA2_RPC_SSL=true
      # - ARIA2_RPC_KEY=/data/ssl/aria2.key
      # - ARIA2_RPC_CERT=/data/ssl/aria2.crt
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    restart: always


