version: '2'
services:
  gitlab:
    build: 'image'
    image: 'gitlab/gitlab-ee:13.7.3-ee.0'
    restart: unless-stopped
    hostname: "$GITLAB_DOMAIN_NAME"
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url "$GITLAB_DOMAIN_URL"
        nginx['redirect_http_to_https'] = true
        nginx['real_ip_header'] = 'X-Real-IP'
        nginx['real_ip_recursive'] = 'on'
        nginx['real_ip_trusted_addresses'] = ["192.168.0.0/16"] #use when behind traefik
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.key'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "$GITLAB_EMAIL_ADDR"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "$GITLAB_EMAIL_USER"
        gitlab_rails['smtp_password'] = "$GITLAB_EMAIL_PWD"
        gitlab_rails['smtp_domain'] = "$GITLAB_EMAIL_DOMAIN"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = '$GITLAB_EMAIL_REPLY'
        gitlab_rails['gravatar_plain_url'] = 'http://cn.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'
        #gitlab_rails['ldap_enabled'] = true
        #gitlab_rails['ldap_servers'] = YAML.load <<-EOS
        #main:
        #  label: 'Gitlab LDAP'
        #  host: 'ldap.example.com'
        #  port: 636
        #  uid: 'sAMAccountName'
        #  uid: 'uid'
        #  encryption: 'simple_tls'
        #  verify_certificates: true
        #  bind_dn: 'CN=admin,CN=Users,Dc=example,Dc=com'
        #  password: 'Password1'
        #  active_directory: true
        #  base: 'OU=GitLab INT,Dc=example,Dc=com'
        #  group_base: 'OU=Global Groups,OU=GitLab INT,Dc=example,Dc=com'
        #  admin_group: 'Global Admins'
        #EOS
        # gitlab_rails['omniauth_allow_single_sign_on'] = ['gitlab']
        # gitlab_rails['omniauth_auto_link_ldap_user'] = true
        # gitlab_rails['omniauth_block_auto_created_users'] = true
        # gitlab_rails['sync_profile_from_provider'] = ['gitlab']
        # gitlab_rails['sync_profile_attributes'] = ['name', 'email']
        # gitlab_rails['omniauth_providers'] = [
        #   {
        #     'name' => 'oauth2_generic',
        #     'app_id' => 'your_oauth_app_id',
        #     'app_secret' => 'your_oauth_secret_key',
        #     'args' => {
        #       scope: "read_user",
        #       client_options: {
        #           'site' => 'https://git.your_server.com', # including port if necessary
        #           'user_info_url' => '/api/v4/user'
        #       },
        #       user_response_structure: {
        #           attributes: {
        #             id: 'id',
        #             user: 'user',
        #             state: 'state',
        #             username: 'username',
        #             email: 'email',
        #           } # if the nickname attribute of a user is called 'username'
        #       },
        #       name: 'bensonfx_oauth'
        #     }
        #   }
        # ]
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    mem_limit: 4096M
    tmpfs:
      - /tmp
    labels:
      - "traefik.enable=true"
      # middlewares
      - "traefik.http.middlewares.custom-headers.headers.contentTypeNosniff=true
      - "traefik.http.middlewares.custom-headers.headers.browserXSSFilter=true
      - "traefik.http.middlewares.custom-headers.headers.browserXSSFilter=true
      - "traefik.http.middlewares.custom-headers.headers.sslRedirect=true
      - "traefik.http.middlewares.behind-proxy-headers.headers.hostsProxyHeaders=X-Forwarded-For"
      # services
      - "traefik.http.services.gitlab.loadBalancer.server.port=80"
      - "traefik.http.services.gitlab.loadBalancer.server.scheme=http"
      - "traefik.http.services.gitlab.loadBalancer.passHostHeader=true"
      # routers
      - "traefik.http.routers.gitlab-web.middlewares=https-redirect@file"
      - "traefik.http.routers.gitlab-web.entrypoints=http"
      - "traefik.http.routers.gitlab-web.rule=Host(`$GITLAB_DOMAIN_NAME`)"
      - "traefik.http.routers.gitlab-https.middlewares=custom-headers,behind-proxy-headers"
      - "traefik.http.routers.gitlab-https.rule=Host(`$GITLAB_DOMAIN_NAME`)"
      - "traefik.http.routers.gitlab-https.tls=true"
