version: '2'
services:
  gitlab:
    build: 'image'
    image: 'bensonfx/gitlab-ce-zh:11.8.1'
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['redirect_http_to_https'] = true
        nginx['real_ip_header'] = 'X-Real-IP'
        nginx['real_ip_recursive'] = 'on'
        nginx['real_ip_trusted_addresses'] = ["192.168.0.0/16"] #use when behind traefik
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.key'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail.example.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "admin@example.com"
        gitlab_rails['smtp_password'] = "your_password"
        gitlab_rails['smtp_domain'] = "example.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'admin@example.com'
        gitlab_rails['gravatar_plain_url'] = 'http://cn.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'
        #gitlab_rails['ldap_enabled'] = true
        #gitlab_rails['ldap_servers'] = YAML.load <<-EOS
        #main:
        #  label: 'Gitlab LDAP'
        #  host: 'ldap.example.com'
        #  port: 636
        #  uid: 'sAMAccountName'
        #  uid: 'uid'
        #  encryption: 'simple_tls'
        #  verify_certificates: true
        #  bind_dn: 'CN=admin,CN=Users,Dc=example,Dc=com'
        #  password: 'Password1'
        #  active_directory: true
        #  base: 'OU=GitLab INT,Dc=example,Dc=com'
        #  group_base: 'OU=Global Groups,OU=GitLab INT,Dc=example,Dc=com'
        #  admin_group: 'Global Admins'
        #EOS
        # gitlab_rails['omniauth_allow_single_sign_on'] = ['gitlab']
        # gitlab_rails['omniauth_auto_link_ldap_user'] = true
        # gitlab_rails['omniauth_block_auto_created_users'] = true
        # gitlab_rails['sync_profile_from_provider'] = ['gitlab']
        # gitlab_rails['sync_profile_attributes'] = ['name', 'email']
        # gitlab_rails['omniauth_providers'] = [
        #   {
        #     'name' => 'oauth2_generic',
        #     'app_id' => 'your_oauth_app_id',
        #     'app_secret' => 'your_oauth_secret_key',
        #     'args' => {
        #       scope: "read_user",
        #       client_options: {
        #           'site' => 'https://git.your_server.com', # including port if necessary
        #           'user_info_url' => '/api/v4/user'
        #       },
        #       user_response_structure: {
        #           attributes: {
        #             id: 'id',
        #             user: 'user',
        #             state: 'state',
        #             username: 'username',
        #             email: 'email',
        #           } # if the nickname attribute of a user is called 'username'
        #       },
        #       name: 'bensonfx_oauth'
        #     }
        #   }
        # ]
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    mem_limit: 4096M
    tmpfs:
      - /tmp
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      #- "traefik.protocol=https"
      - "traefik.frontend.passTLSCert=false"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.rule=Host:gitlab.example.com"
      - "traefik.docker.network=traefik"
