version: '2'
services:
  gitlab:
    build: 'image'
    image: 'bensonfx/gitlab-ce-zh:11.3.6'
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['redirect_http_to_https'] = true
        nginx['real_ip_header'] = 'X-Real-IP'
        nginx['real_ip_recursive'] = 'on'
        nginx['real_ip_trusted_addresses'] = ["192.168.0.0/16"] #use when behind traefik
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.key'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail.example.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "admin@example.com"
        gitlab_rails['smtp_password'] = "your_password"
        gitlab_rails['smtp_domain'] = "example.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'admin@example.com'
        gitlab_rails['gravatar_plain_url'] = 'http://cn.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    mem_limit: 4096M
    tmpfs:
      - /tmp
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      #- "traefik.protocol=https"
      - "traefik.frontend.passTLSCert=false"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.rule=Host:gitlab.example.com"
      - "traefik.docker.network=traefik"
