#!/bin/bash

CWD=$(pwd)
COMPOSE_FILE=${CWD}/docker-compose.yml
DOCKER_FILE=${CWD}/image/Dockerfile

if [ $# -eq 0 ];then
    echo "$0 new_version"
fi

new_version=$1

sed -ri "s@bensonfx/gitlab-ce-zh:[0-9.]+@bensonfx/gitlab-ce-zh:${new_version}@g" ${COMPOSE_FILE}
sed -ri "s@gitlab/gitlab-ce:[0-9.]+@gitlab/gitlab-ce:${new_version}@g" ${DOCKER_FILE}
sed -ri "s@GITLAB_VERSION=[0-9.]+@GITLAB_VERSION=${new_version}@g" ${DOCKER_FILE}

