#!/bin/bash

CWD=$(pwd)
COMPOSE_FILE=${CWD}/docker-compose.yml
DOCKER_FILE=${CWD}/image/Dockerfile

if [ $# -eq 0 ];then
    echo "$0 new_version"
fi

new_version=$1

sed -i "s@bensonfx/gitlab-ce-zh:.*@bensonfx/gitlab-ce-zh:${new_version}\'@g" ${COMPOSE_FILE}
sed -i "s@gitlab/gitlab-ce:.*@gitlab/gitlab-ce:${new_version}-ce.0@g" ${DOCKER_FILE}
sed -i "s@^ENV GITLAB_VERSION=.*@ENV GITLAB_VERSION=${new_version}@g" ${DOCKER_FILE}

