version: '3.1'
services:
  zentao:
    image: bensonfx/zentao:10.4
    build: image
    restart: unless-stopped
    depends_on:
      - mysql
    working_dir: /wwwroot
    environment:
      ZENTAO_SERVER: example.com
      ZENTAO_ROOT: /wwwroot/zentaopms/www
    volumes:
      - ./wwwroot:/wwwroot/zentaopms
      - ./ssl:/wwwroot/ssl
    ports:
      #- "443:443"
      #- "80:80"
  mysql:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: zentao
      MYSQL_USER: zentaoDB
      MYSQL_PASSWORD: your_zentao_password
    volumes:
      - ./mysql:/var/lib/mysql
